$('.domainlogo img').hide()
$('#mb1').hide()
$('#vr-proto-header').hide()
$('#vr-proto-nav').css('padding', '0')
$('#nav').css('margin', '0').css('width', '130px')
$('#mainbody').css('margin-left', '140px')
